### ISSUE TITLE
missing assets in pip package

### ISSUE THREAD

**Issue by gbiscuolo** [shreyanshk/boottorrent#15]
* boottorrent version: 0.1.0
* Python version: 3.6
* Operating System: Debian stable/testing

### Description

I was trying to init a new boottorrent project but the command ended with an error since assets are not included in package

### What I Did

I installed dependences then [installed boottorrent via pip](https://boottorrent.readthedocs.io/en/latest/installation.html#from-pip), please see [my deployment notes](https://github.com/shreyanshk/boottorrent/blob/dev/GSoC-2018/deployment-notes-GB.org) for details, if needed

after `boottorrent` installation I did:
 
```
$ boottorrent init boottest
Traceback (most recent call last):
  File "/usr/local/bin/boottorrent", line 11, in <module>
    load_entry_point('boottorrent==0.1.0', 'console_scripts', 'boottorrent')()
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/boottorrent/cli.py", line 24, in init
    copy_tree(base, nfolder)
  File "/usr/lib/python3.6/distutils/dir_util.py", line 127, in copy_tree
    "cannot copy tree '%s': not a directory" % src)
distutils.errors.DistutilsFileError: cannot copy tree '/usr/local/lib/python3.6/dist-packages/boottorrent/assets/skel': not a directory
```

**Comment by shreyanshk** [comment]
I think I've fixed it.
Consider retrying. Thank you.

**Comment by gbiscuolo** [comment]
fine! now "boottorrent init" it's working as documented.
Ciao
Giovanni
