### ISSUE TITLE
in "quick start", file not found, it searches in the wrong dir?

### ISSUE THREAD

**Issue by atrent** [shreyanshk/boottorrent#21]
I'm following the instructions in https://boottorrent.readthedocs.io/en/latest/quickstart.html#booting-the-kernel and I get this:

$ boottorrent start
Traceback (most recent call last):
  File "/usr/local/bin/boottorrent", line 11, in <module>
    load_entry_point('boottorrent==0.1.0', 'console_scripts', 'boottorrent')()
  File "/usr/local/lib/python3.6/dist-packages/click-6.7-py3.6.egg/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click-6.7-py3.6.egg/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/click-6.7-py3.6.egg/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/dist-packages/click-6.7-py3.6.egg/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/click-6.7-py3.6.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/boottorrent-0.1.0-py3.6.egg/boottorrent/cli.py", line 43, in start
    bt.start()
  File "/usr/local/lib/python3.6/dist-packages/boottorrent-0.1.0-py3.6.egg/boottorrent/boottorrent.py", line 72, in start
    self.generate_client_config()
  File "/usr/local/lib/python3.6/dist-packages/boottorrent-0.1.0-py3.6.egg/boottorrent/boottorrent.py", line 276, in generate_client_config
    osconfig = open(f"{self.wd}/oss/{os}/config.yaml", "r").read()
FileNotFoundError: [Errno 2] No such file or directory: '/home/bt/boottorrent/bootprova/oss/a/config.yaml'

I have created the:
bootprova/oss
bootprova/oss/README.rst
bootprova/oss/atrent-test
bootprova/oss/atrent-test/config.yaml
bootprova/oss/atrent-test/initramfs-linux-lts.img
bootprova/oss/atrent-test/vmlinuz-linux-lts

And I'm launching 'boottorrent start' while in dir 'bootprova', here are the config files:

$ cat Boottorrent.yaml
boottorrent:
  version: 0
  timeout: 30
  seed_time: 0
  default_os: atrent-test
  host_ip: 192.168.1.1
  display_oss: atrent-test
  #    - testos
  #    - freedos

dnsmasq:
  enable_dhcp: True
  enable_tftp: True
  interface: eth0
  bind_interfaces: True
  dhcp_range: "192.168.1.50,192.168.1.150,12h"
  #user: shreyansh

hefur:
    enable: True
    port: 10001

transmission:
  rpc_port: 9091

aria2:
    bt_enable_lpd: True
    check_integrity: True
    enable_dht: False
    enable_dht6: False
    enable_peer_exchange: True

$ cat oss/atrent-test/config.yaml 
dispname: atrent-test
method: kexec
kernel: vmlinuz-linux-lts
initrd: initramfs-linux-lts.img
cmdline: break

**Comment by shreyanshk** [comment]
Please note that display_oss is a list of strings (as specified in the docs).
It is currently being given as a string and not array/list of strings.
Please update the value to either ``display_oss: [atrent-test]`` or like this
```
display_oss:
  - atrent-test
```

**Comment by atrent** [comment]
this is what's written in the quick start:

Next, you need to explicitly tell BootTorrent to enable this OS.

Boottorrent.yaml
boottorrent:
    ...
    display_oss: linuxos
    default_os: linuxos
    ...

**Comment by shreyanshk** [comment]
I see. It's an overlook on my sight. I'll fix it.
Please confirm that ``display_oss: [atrent-test]`` or equivalent works on your computer.

**Comment by shreyanshk** [comment]
I've updated it. (81dadf6f0cb5ff4021295e5900b279048c06a8a9)

**Comment by atrent** [comment]
it works
