### ISSUE TITLE
(from clean install) error in starting boottorrent

### ISSUE THREAD

**Issue by atrent** [shreyanshk/boottorrent#29]
- untouched files, from commit 70630c1a006b79e1eb54b49ea080b909bcba31a6
- inside virtualenv

(venv) bt@boottorrent:~/boottorrent/envtest$ sudo boottorrent start
Traceback (most recent call last):
  File "/usr/local/bin/boottorrent", line 11, in <module>
    load_entry_point('boottorrent==0.1.0', 'console_scripts', 'boottorrent')()                                                                
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 480, in load_entry_point                                            
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2691, in load_entry_point                                           
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2322, in load                                                       
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2328, in resolve                                                    
    module = __import__(self.module_name, fromlist=['__name__'], level=0)                                                                     
  File "/usr/local/lib/python2.7/dist-packages/boottorrent/__init__.py", line 9, in <module>                                                  
    from .boottorrent import BootTorrent  # noqa
  File "/usr/local/lib/python2.7/dist-packages/boottorrent/boottorrent.py", line 117                                                          
    print(line, end="")
                   ^
SyntaxError: invalid syntax

The problem is sudo of course, but I tried to activate virtualenv after a 'sudo su -' (changing to the venv dir), same error

**Comment by atrent** [comment]
I had to uninstall boottorrent because when I installed it using sudo the venv was bypassed, I should have thought about it.
It should be warned in the doc.

**Comment by shreyanshk** [comment]
I've added a note (a8f8f5b4029ba71f8171472a2ccf950be0c970f4).
